name: family_bridge
description: HIPAA-compliant family health management application with comprehensive security infrastructure
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI
  cupertino_icons: ^1.0.6
  
  # Backend & Database
  supabase_flutter: ^2.0.0
  
  # Security & Encryption
  encrypt: ^5.0.1
  crypto: ^3.0.3
  
  # Authentication
  local_auth: ^2.1.6
  otp: ^3.1.4
  
  # Device Information
  device_info_plus: ^9.1.0
  
  # Utilities
  uuid: ^4.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # Networking
  http: ^1.1.0
  dio: ^5.4.0
  
  # State Management (optional, choose one)
  provider: ^6.1.1
  # riverpod: ^2.4.9
  # bloc: ^8.1.2
  
  # Date/Time
  intl: ^0.18.1
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Notifications
  flutter_local_notifications: ^16.2.0
  
  # Image handling
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  
  # Charts for health data
  fl_chart: ^0.65.0
  
  # QR Code for MFA setup
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # File operations
  file_picker: ^6.1.1
  
  # PDF generation for reports
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Form validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7
  
  # Code generation
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  
  # Integration testing
  integration_test:
    sdk: flutter
  
  # Security testing
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/certificates/
  
  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Light.ttf
          weight: 300
    
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600

# Platform-specific configurations
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"