name: family_bridge
description: Multi-generational family care coordination app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  
  # Supabase for backend
  supabase_flutter: ^2.5.6
  
  # UI and animations
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  
  # Media handling
  image_picker: ^1.0.7
  video_player: ^2.8.3
  audioplayers: ^6.0.0
  record: ^5.0.4
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  connectivity_plus: ^5.0.2
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Chat features
  emoji_picker_flutter: ^2.1.1
  giphy_get: ^3.5.6
  flutter_linkify: ^6.0.0
  
  # Voice and speech
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700