name: family_bridge
description: Multi-generational family care coordination app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  
  # Supabase for backend
  supabase_flutter: ^2.5.6
  
  # UI and animations
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # Navigation
  go_router: ^13.0.0
  
  # Data & Backend
  supabase_flutter: ^2.3.2
  shared_preferences: ^2.2.2
  http: ^1.1.2
  dio: ^5.4.0
  
  # Media handling
  image_picker: ^1.0.7
  video_player: ^2.8.3
  audioplayers: ^6.0.0
  record: ^5.0.4
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  connectivity_plus: ^5.0.2
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  # Health & Fitness
  percent_indicator: ^4.2.3
  fl_chart: ^0.66.2
  
  # Professional reporting
  pdf: ^3.10.7
  printing: ^5.12.0
  
  # HIPAA Compliance & Security
  encrypt: ^5.0.1
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^9.1.1
  
  # Icons
  flutter_feather_icons: ^2.0.0+1
  
  # Media
  audioplayers: ^5.2.1
  image_picker: ^1.0.5
  camera: ^0.10.5
  record: ^5.0.4
  
  # Permissions & Device
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Voice & Speech
  speech_to_text: ^6.4.1
  flutter_tts: ^4.0.2

  # Forms
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  
  # Chat features
  emoji_picker_flutter: ^2.1.1
  giphy_get: ^3.5.6
  flutter_linkify: ^6.0.0
  
  # Voice and speech
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2

  # Utilities
  uuid: ^4.2.2
  collection: ^1.18.0
  flutter_dotenv: ^5.1.0

  # Weather (optional)
  weather: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/sounds/
  
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700