name: family_bridge
description: An intergenerational care coordination mobile application designed to bridge the technology gap between elderly family members, their caregivers, and younger family members.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  supabase_flutter: ^2.5.6
  
  provider: ^6.1.2
  
  speech_to_text: ^6.6.2
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1
  
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  
  url_launcher: ^6.3.0
  
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
  shared_preferences: ^2.2.3
  
  intl: ^0.19.0
  
  cached_network_image: ^3.3.1
  
  flutter_local_notifications: ^17.2.1+2
  
  connectivity_plus: ^6.0.3
  
  health: ^10.2.0
  
  flutter_svg: ^2.0.10+1
  
  google_fonts: ^6.2.1
  
  uuid: ^4.4.0
  
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
