name: family_bridge
description: An intergenerational care coordination mobile application
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.0
  flutter_riverpod: ^2.0.0
  
  # Backend & Database
  supabase_flutter: ^1.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Design
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  
  # Networking
  http: ^0.13.0
  dio: ^5.0.0
  
  # Audio & Media
  flutter_sound: ^9.2.13
  image_picker: ^0.8.7+4
  permission_handler: ^10.2.0
  
  # Authentication & Security
  crypto: ^3.0.2
  
  # Utilities
  intl: ^0.18.0
  uuid: ^3.0.7
  path_provider: ^2.0.14
  shared_preferences: ^2.0.18
  
  # Speech & Voice
  speech_to_text: ^6.3.0
  flutter_tts: ^3.6.3
  
  # Push Notifications
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^14.1.0
  
  # Health Data Integration
  health: ^9.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700