# FamilyBridge Security Configuration
# Comprehensive security settings for production healthcare environment

security:
  # Encryption Configuration
  encryption:
    at_rest:
      algorithm: "AES-256-GCM"
      key_rotation_days: 90
      key_management: "AWS KMS" # or "Azure Key Vault" or "Google Cloud KMS"
      key_derivation: "PBKDF2-SHA256"
      salt_length: 32
    
    in_transit:
      tls_version: "1.3"
      cipher_suites:
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_CHACHA20_POLY1305_SHA256"
        - "TLS_AES_128_GCM_SHA256"
      certificate_pinning: true
      hsts_enabled: true
      hsts_max_age: 31536000 # 1 year
    
    database:
      encrypted_columns:
        - user_profiles.medical_data
        - messages.content
        - daily_checkins.health_data
        - medications.dosage_info
        - emergency_contacts.phone_numbers
      
      field_level_encryption: true
      backup_encryption: true
      log_encryption: true

  # Authentication & Authorization
  authentication:
    multi_factor:
      enabled: true
      required_for_roles: ["caregiver", "admin", "healthcare_professional"]
      methods:
        - "sms"
        - "email"
        - "authenticator_app"
        - "biometric"
      
      backup_codes: 10
      session_timeout: 1800 # 30 minutes
      max_concurrent_sessions: 3
    
    password_policy:
      min_length: 12
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_special_chars: true
      prevent_common_passwords: true
      password_history: 12
      max_age_days: 90
    
    account_lockout:
      max_failed_attempts: 5
      lockout_duration: 900 # 15 minutes
      progressive_delays: true
    
    biometric_auth:
      enabled: true
      fallback_to_password: true
      supported_types:
        - fingerprint
        - face_recognition
        - voice_recognition

  # Access Control
  access_control:
    role_based_access:
      enabled: true
      roles:
        elder:
          permissions:
            - read_own_data
            - write_daily_checkin
            - send_family_messages
            - view_own_medication
          data_access_level: "personal"
        
        caregiver:
          permissions:
            - read_family_data
            - write_care_plans
            - manage_appointments
            - view_health_reports
          data_access_level: "family"
        
        youth:
          permissions:
            - read_family_messages
            - send_family_messages
            - view_public_family_data
          data_access_level: "limited"
        
        healthcare_professional:
          permissions:
            - read_patient_data
            - write_medical_notes
            - generate_reports
            - manage_care_plans
          data_access_level: "professional"
          requires_license_verification: true
        
        admin:
          permissions:
            - manage_users
            - view_audit_logs
            - system_configuration
            - compliance_reports
          data_access_level: "administrative"
          requires_background_check: true
    
    attribute_based_access:
      enabled: true
      attributes:
        - user_location
        - device_trust_level
        - time_of_access
        - data_sensitivity_level
        - user_clearance_level
    
    minimum_necessary_access:
      enabled: true
      automatic_access_review: true
      review_frequency_days: 90
      unused_access_removal: true

  # Network Security
  network:
    firewall:
      enabled: true
      default_policy: "deny"
      allowed_ports:
        - 80   # HTTP (redirects to HTTPS)
        - 443  # HTTPS
        - 5432 # PostgreSQL (internal only)
      
      rate_limiting:
        requests_per_minute: 1000
        burst_limit: 100
        whitelist_ips: []
    
    ddos_protection:
      enabled: true
      threshold_requests_per_second: 1000
      mitigation_actions:
        - "rate_limit"
        - "challenge"
        - "block"
    
    api_security:
      api_key_required: true
      api_versioning: true
      input_validation: true
      output_sanitization: true
      sql_injection_protection: true
      xss_protection: true
      csrf_protection: true

  # Data Loss Prevention
  data_loss_prevention:
    enabled: true
    policies:
      - name: "PHI Data Protection"
        description: "Prevent unauthorized PHI data access and transfer"
        rules:
          - block_unencrypted_phi_transfer
          - require_approval_for_phi_export
          - log_all_phi_access
        
      - name: "Insider Threat Detection"
        description: "Detect unusual data access patterns"
        rules:
          - alert_on_bulk_data_access
          - detect_off_hours_access
          - monitor_privileged_user_activity
    
    content_scanning:
      enabled: true
      scan_types:
        - medical_record_numbers
        - social_security_numbers
        - phone_numbers
        - email_addresses
        - medication_names
    
    watermarking:
      enabled: true
      watermark_sensitive_documents: true
      track_document_access: true

# Compliance Configuration
compliance:
  hipaa:
    enabled: true
    
    # Administrative Safeguards
    administrative:
      security_officer_assigned: true
      workforce_training_required: true
      access_management_procedures: true
      information_access_management: true
      security_awareness_training: true
      security_incident_procedures: true
      contingency_plan: true
      periodic_security_evaluation: true
      business_associate_agreements: true
    
    # Physical Safeguards
    physical:
      facility_access_controls: true
      workstation_use_restrictions: true
      device_and_media_controls: true
      data_backup_and_storage: true
    
    # Technical Safeguards
    technical:
      access_control: true
      audit_controls: true
      integrity_controls: true
      person_or_entity_authentication: true
      transmission_security: true
    
    # Audit Requirements
    audit:
      log_all_phi_access: true
      log_retention_years: 7
      tamper_protection: true
      automated_log_analysis: true
      regular_audit_reports: true
      
      audit_events:
        - user_login_logout
        - data_access_attempts
        - system_configuration_changes
        - privilege_escalations
        - failed_authentication_attempts
        - data_exports
        - system_errors
        - security_incidents
    
    # Breach Detection and Response
    breach_detection:
      enabled: true
      real_time_monitoring: true
      automated_response: true
      
      detection_rules:
        - multiple_failed_logins
        - unusual_data_access_patterns
        - off_hours_system_access
        - bulk_data_downloads
        - unauthorized_device_access
        - privilege_escalation_attempts
      
      response_procedures:
        immediate_actions:
          - isolate_affected_systems
          - preserve_audit_logs
          - notify_security_team
          - document_incident
        
        investigation_actions:
          - forensic_analysis
          - impact_assessment
          - root_cause_analysis
          - remediation_planning
        
        notification_requirements:
          - internal_stakeholders: "immediate"
          - affected_individuals: "60 days"
          - hhs_ocr: "60 days"
          - media_if_required: "varies"

  # GDPR Compliance
  gdpr:
    enabled: true
    
    data_protection:
      privacy_by_design: true
      data_minimization: true
      purpose_limitation: true
      accuracy_principle: true
      storage_limitation: true
      
      retention_periods:
        user_profiles: "7 years after last activity"
        health_data: "7 years after generation"
        audit_logs: "7 years"
        communication_data: "3 years"
        session_data: "30 days"
    
    individual_rights:
      right_of_access: true
      right_to_rectification: true
      right_to_erasure: true
      right_to_restrict_processing: true
      right_to_data_portability: true
      right_to_object: true
    
    consent_management:
      explicit_consent_required: true
      consent_withdrawal_process: true
      consent_record_keeping: true
      granular_consent_options: true

# Incident Response
incident_response:
  enabled: true
  
  team_contacts:
    security_officer:
      name: "Chief Security Officer"
      email: "cso@familybridge.com"
      phone: "+1-xxx-xxx-xxxx"
      escalation_level: 1
    
    compliance_officer:
      name: "Chief Compliance Officer"
      email: "compliance@familybridge.com"
      phone: "+1-xxx-xxx-xxxx"
      escalation_level: 1
    
    technical_lead:
      name: "CTO"
      email: "cto@familybridge.com"
      phone: "+1-xxx-xxx-xxxx"
      escalation_level: 2
  
  severity_levels:
    critical:
      description: "System compromise, data breach, or service outage"
      response_time: "15 minutes"
      escalation_path: ["security_officer", "compliance_officer", "ceo"]
      external_notifications: ["customers", "regulators", "law_enforcement"]
    
    high:
      description: "Security vulnerability or service degradation"
      response_time: "1 hour"
      escalation_path: ["security_officer", "technical_lead"]
      external_notifications: ["customers"]
    
    medium:
      description: "Policy violation or minor security issue"
      response_time: "4 hours"
      escalation_path: ["security_officer"]
      external_notifications: []
    
    low:
      description: "Security awareness or process improvement"
      response_time: "24 hours"
      escalation_path: ["security_team"]
      external_notifications: []
  
  playbooks:
    data_breach:
      immediate_actions:
        - isolate_affected_systems
        - preserve_evidence
        - assess_scope_of_breach
        - notify_incident_response_team
      
      investigation_actions:
        - conduct_forensic_analysis
        - determine_root_cause
        - assess_impact_to_individuals
        - document_all_findings
      
      remediation_actions:
        - implement_security_patches
        - enhance_monitoring
        - update_security_policies
        - provide_additional_training
      
      communication_actions:
        - prepare_breach_notification
        - notify_affected_individuals
        - report_to_regulators
        - coordinate_public_response
    
    system_compromise:
      immediate_actions:
        - disconnect_compromised_systems
        - activate_backup_systems
        - change_all_credentials
        - implement_emergency_access_controls
      
      recovery_actions:
        - rebuild_compromised_systems
        - restore_from_clean_backups
        - validate_system_integrity
        - gradually_restore_services

# Security Testing
security_testing:
  penetration_testing:
    frequency: "quarterly"
    scope: "full_application_and_infrastructure"
    third_party_required: true
    
    test_types:
      - network_penetration_testing
      - web_application_testing
      - mobile_application_testing
      - social_engineering_testing
      - physical_security_testing
  
  vulnerability_scanning:
    frequency: "weekly"
    automated: true
    tools:
      - "OWASP ZAP"
      - "Nessus"
      - "Snyk"
      - "SonarQube"
    
    scan_types:
      - static_code_analysis
      - dynamic_application_testing
      - dependency_vulnerability_scanning
      - infrastructure_scanning
  
  security_code_review:
    required_for_all_changes: true
    automated_tools: true
    manual_review_required: true
    
    focus_areas:
      - authentication_and_authorization
      - input_validation
      - output_encoding
      - cryptographic_implementations
      - error_handling
      - logging_and_monitoring