name: family_bridge
description: A comprehensive family connection and elder care application
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core packages
  cupertino_icons: ^1.0.6
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # State management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # Network
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  
  # Backend
  supabase_flutter: ^2.3.0
  
  # Security
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # Utilities
  path_provider: ^2.1.1
  uuid: ^4.2.2
  intl: ^0.18.1
  collection: ^1.18.0
  
  # Image handling
  cached_network_image: ^3.3.1
  image: ^4.1.3
  flutter_image_compress: ^2.1.0
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Background processing
  workmanager: ^0.5.2
  flutter_local_notifications: ^16.3.0
  
  # Analytics
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700